input <- setClass("input", 
         slots = c(spatial = "numeric", 
                   zero = "numeric", 
                   # mc = "numeric", 
                   folder = "character", 
                   folderOutput = "character",
                   cores = "numeric", 
                   ww = "list", 
                   inf = "list", 
                   rw = "list", 
                   tf = "numeric", 
                   P1 = "data.frame",
                   st = "list",
                   export = "numeric"),
         prototype = list(spatial = 0,
                       zero = 1E-5,
                       # mc = 0,
                       folder = system.file("shiny", package = "EmiStatR"),
                       folderOutput = system.file("shiny", package = "EmiStatR"),
                       cores = 1,
                       ww = NULL,
                       inf = NULL,
                       rw = NULL,
                       tf = NULL,
                       P1 = NULL,
                       st = NULL,
                       export = 1)
         )